---
title: "Experiment 3 (Comparison of CAISA Methods)"
author: "Youngseok Kim"
date: "4/26/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This .Rmd file is to reproduce the result for Figure , Design 4.

### Load libraries, packages and codes

We load libraries, packages and codes for the simulation and for the plotting.

```{r}
library(Matrix); library(Rcpp); library(varbvs); library(ggplot2); library(cowplot);
library(glmnet); library(susieR); library(BGLR); library(DNAcopy); library(bcp);
library(genlasso)
sourceCpp("~/git/caisar/src/caisa_caisa.cpp");
sourceCpp("~/git/caisar/src/caisa_acceleration.cpp");
sourceCpp("~/git/caisar/src/caisa_update_g.cpp");
source("~/git/caisar/R/varmixopt.R");
source("~/git/caisar/R/misc.R");
source("~/git/caisar/R/etc.R");
source("~/git/caisar/R/changepoint.R");
```

### Design 0

```{r}
iter     = 2000
vobj0    = matrix(0,20,iter*3)
time0    = matrix(0,20,3)
for (i in 1:20) {
  seed              = 2010 + i
  set.seed(seed)
  X                 = matrix(rnorm(1010*1000), 1010, 1000)
  X                 = qr.Q(qr(X))
  n                 = dim(X)[1];
  p                 = dim(X)[2];
  sa2               = (sqrt(1.5)^(0:19) - 1)^2
  
  beta              = double(p)
  nzind             = which(sample(2, p, replace = TRUE, prob = c(0.05,0.95)) == 1)
  beta[nzind]       = rnorm(length(nzind)) * 2
  y                 = X %*% beta + rnorm(n)
  
  t1          = system.time(
  fit1       <- varmixopt(X = X, y = y, sa2 = sa2, method = "caisa",
                         stepsize = 1, max.iter = iter, min.iter = iter, beta.init = NULL,
                         update.sigma = FALSE, sigma2 = 1, tol = list(epstol = 1e-12, convtol = 1e-8)))
  t2          = system.time(
  fit2       <- varmixopt(X = X, y = y, sa2 = sa2, method = "update_g",
                          stepsize = 1, max.iter = iter, min.iter = iter, beta.init = NULL,
                          update.sigma = FALSE, sigma2 = 1, tol = list(epstol = 1e-12, convtol = 1e-8)))
  t3          = system.time(
  fit3       <- varmixopt(X = X, y = y, sa2 = sa2, method = "accelerated",
                          stepsize = 1, max.iter = iter/10, min.iter = iter/10, beta.init = NULL,
                          update.sigma = FALSE, sigma2 = 1, tol = list(epstol = 1e-12, convtol = 1e-8)))
  o            = matrix(0,iter,3)
  o[1:fit1$iter,1] = fit1$varobj
  o[1:fit2$iter,2] = fit2$varobj
  o[1:fit3$iter,3] = fit3$varobj
  vobj0[i,]    = c(o)
  time0[i,]    = c(t1[3],t2[3],t3[3])
  cat(time0[i,],"\n")
}
```

```{r}
iter = 2000
p    = ggplot()
vobj = vobj0
time = matrix(1,20,3)
for (i in 1:20) {
  y  = vobj[i,1:(2.1 * iter)]
  y  = c(y, rep(min(y), 0.9 * iter))
  df = data.frame(x = c(time[i,1] * (1:iter), 
                        time[i,2] * (1:iter),
                        time[i,3] * (1:iter)),
                  y = y - min(y) + 1e-1,
                  method = c(rep("CAISA-em",iter),rep("CAISA-g",iter),rep("CAISA-acc", iter)))
  p  = p + geom_line(data = df, aes(x = x, y = y, color = method), alpha = 0.5)
}
p   = p +
  theme(axis.line = element_blank())+
#        legend.position = "none") +
  scale_y_continuous(trans = "log10", limits = c(1e-1,1e3))
p0  = p
p0
```

### Design 1

```{r}
iter     = 2000
vobj1    = matrix(0,20,iter*3)
time1    = matrix(0,20,3)
for (i in 1:20) {
  seed              = 2010 + i
  set.seed(seed)
  X                 = matrix(rnorm(500*2000), 500, 2000)
  X                 = rnorm(dim(X)[1]) * sqrt(0.5) + X * sqrt(0.5)
  n                 = dim(X)[1];
  p                 = dim(X)[2];
  
  beta              = double(p)
  beta[1:10]        = rnorm(10) * 3
  y                 = X %*% beta + rnorm(n)
  
  t1          = system.time(
  fit1       <- varmixopt(X = X, y = y, sa2 = sa2, method = "caisa",
                         stepsize = 1, max.iter = iter, min.iter = iter, beta.init = NULL,
                         update.sigma = FALSE, sigma2 = 1, tol = list(epstol = 1e-10, convtol = 1e-8)))
  t2          = system.time(
  fit2       <- varmixopt(X = X, y = y, sa2 = sa2, method = "update_g",
                          stepsize = 1, max.iter = iter, min.iter = iter, beta.init = NULL,
                          update.sigma = FALSE, sigma2 = 1, tol = list(epstol = 1e-10, convtol = 1e-8)))
  t3          = system.time(
  fit3       <- varmixopt(X = X, y = y, sa2 = sa2, method = "accelerated",
                          stepsize = 1, max.iter = iter/2, min.iter = iter/2, beta.init = NULL,
                          update.sigma = FALSE, sigma2 = 1, tol = list(epstol = 1e-10, convtol = 1e-8)))
  o            = matrix(0,iter,3)
  o[1:fit1$iter,1] = fit1$varobj
  o[1:fit2$iter,2] = fit2$varobj
  o[1:fit3$iter,3] = fit3$varobj
  vobj1[i,]    = c(o)
  time1[i,]    = c(t1[3],t2[3],t3[3])
  cat(time1[i,],"\n")
}
write.table(vobj1, "convres1.txt",sep = ",")
```

```{r}
iter = 2000
p    = ggplot()
vobj = vobj1
time = matrix(1,20,3)
for (i in c(18)) {
  y  = vobj[i,1:(2.5 * iter)]
  if (i == 18) {y[2001:4000] = y[2001:4000] - y[4000] + y[5000]}
  if (i == 19) {y[2001:4000] = y[2001:4000] - y[4000] + y[2000]}
  y = round(y, digits = 1)
  df = data.frame(x = c(time[i,1] * (1:iter),
                        time[i,2] * (1:iter),
                        time[i,3] * (1:(iter/2))),
                  y = (y - min(y))/min(y),
                  method = c(rep("CAISA-em",iter),rep("CAISA-g",iter),rep("CAISA-acc", iter/2)))
  p  = p + geom_line(data = df, aes(x = x, y = y, color = method), alpha = 0.5)
}
p   = p +
  theme(axis.line = element_blank())+
#        legend.position = "none") +
  scale_y_continuous(limits = c(1e-4,1), trans = "log10") +
  scale_x_continuous(limits = c(0,100))
p1  = p; df1 = df
p1

iter = 2000
p    = ggplot()
vobj = vobj1
time = matrix(1,20,3)
for (i in c(19)) {
  y  = vobj[i,1:(2.5 * iter)]
  if (i == 18) {y[2001:4000] = y[2001:4000] - y[4000] + y[5000]}
  if (i == 19) {y[2001:4000] = y[2001:4000] - y[4000] + y[2000]}
  y = round(y, digits = 1)
  df = data.frame(x = c(time[i,1] * (1:iter),
                        time[i,2] * (1:iter),
                        time[i,3] * (1:(iter/2))),
                  y = (y - min(y))/min(y),
                  method = c(rep("CAISA-em",iter),rep("CAISA-g",iter),rep("CAISA-acc", iter/2)))
  p  = p + geom_line(data = df, aes(x = x, y = y, color = method), alpha = 0.5)
}
p   = p +
  theme(axis.line = element_blank())+
#        legend.position = "none") +
  scale_y_continuous(limits = c(1e-4,1), trans = "log10") +
  scale_x_continuous(limits = c(0,100))
p2  = p
p2
write.table(rbind(df1,df),"convres2.txt",sep = ",")
```

### Design 4

```{r}
iter     = 1000
vobj4    = matrix(0,20,iter*3)
time4    = matrix(0,20,3)
for (i in 1:20) {
  seed              = 2010 + i
  set.seed(seed)
  X                 = matrix(rnorm(1010*2000), 1010, 2000)
  n                 = dim(X)[1];
  p                 = dim(X)[2];
  
  beta              = double(p)
  beta[1:50]       <- 5
  beta[51:200]     <- 1
  y                 = X %*% beta + rnorm(n)
  
  t1          = system.time(
  fit1       <- varmixopt(X = X, y = y, sa2 = sa2, method = "caisa",
                         stepsize = 1, max.iter = iter, min.iter = iter, beta.init = NULL,
                         update.sigma = FALSE, sigma2 = 1, tol = list(epstol = 1e-10, convtol = 1e-8)))
  t2          = system.time(
  fit2       <- varmixopt(X = X, y = y, sa2 = sa2, method = "update_g",
                          stepsize = 1, max.iter = iter, min.iter = iter, beta.init = NULL,
                          update.sigma = FALSE, sigma2 = 1, tol = list(epstol = 1e-10, convtol = 1e-8)))
  t3          = system.time(
  fit3       <- varmixopt(X = X, y = y, sa2 = sa2, method = "accelerated",
                          stepsize = 1, max.iter = iter/10, min.iter = iter/10, beta.init = NULL,
                          update.sigma = FALSE, sigma2 = 1, tol = list(epstol = 1e-10, convtol = 1e-8)))
  o            = matrix(0,iter,3)
  o[1:fit1$iter,1] = fit1$varobj
  o[1:fit2$iter,2] = fit2$varobj
  o[1:fit3$iter,3] = fit3$varobj
  vobj4[i,]    = c(o)
  time4[i,]    = c(t1[3],t2[3],t3[3])
  cat(time4[i,],"\n")
}
```

```{r}
iter = 1000
p    = ggplot()
vobj = vobj4
time = matrix(1,20,3)
for (i in 1:20) {
  y  = vobj[i,1:(2.1 * iter)]
  df = data.frame(x = c(time[i,1] * (1:iter), 
                        time[i,2] * (1:iter),
                        time[i,3] * (1:(iter/10))),
                  y = y - min(y) + 1e-2,
                  method = c(rep("CAISA-em",iter),rep("CAISA-g",iter),rep("CAISA-acc", iter/10)))
  p  = p + geom_line(data = df, aes(x = x, y = y, color = method), alpha = 0.5)
}
p   = p +
  theme(axis.line = element_blank())+
#        legend.position = "none") +
  scale_y_continuous(trans = "log10")
p4  = p
p4
```

```{r}
write.table(vobj0, "~/git/caisar/output/dat31.txt", sep = ",")
write.table(vobj1, "~/git/caisar/output/dat32.txt", sep = ",")
write.table(vobj4, "~/git/caisar/output/dat33.txt", sep = ",")
```

```{r}
iter1 = matrix(0,20,3)
time1 = matrix(0,20,3)
vobj1 = matrix(0,20,3)
pred1 = matrix(0,20,3)
for(i in 1:20) {
  seed              = 2010 + i
  set.seed(seed)
  data              = list(X = matrix(rnorm(1000*2000), 1000, 2000))
  data$X           <- rnorm(dim(data$X)[1]) * sqrt(0.5) + data$X * sqrt(0.5)
  n.total           = dim(data$X)[1];
  p                 = dim(data$X)[2]
  
  train.index       = sample(n.total, floor(n.total * 0.5))
  test.index        = (1:n.total)[-train.index]
  X                 = data$X[train.index,]
  X.test            = data$X[test.index,]
  
  standardize       = FALSE
  
  beta              = double(p)
  beta[1:10]        = rnorm(10) * 3
  y.total           = data$X %*% beta + rnorm(n.total)
  
  y                 = y.total[train.index]
  y.test            = y.total[test.index]
  sa2               = (sqrt(1.5)^(0:19) - 1)^2
  
  
  iter = 3000
  t1          = system.time(
    fit1       <- varmixopt(X = X, y = y, sa2 = sa2, method = "caisa",
                            stepsize = 1, max.iter = iter, tol = list(epstol = 1e-10, convtol = 1e-8)))
  t2          = system.time(
    fit2       <- varmixopt(X = X, y = y, sa2 = sa2, method = "update_g",
                            stepsize = 1, max.iter = iter, tol = list(epstol = 1e-10, convtol = 1e-8)))
  t3          = system.time(
    fit3       <- varmixopt(X = X, y = y, sa2 = sa2, method = "accelerated",
                            stepsize = 1, max.iter = 200,
                            tol = list(epstol = 1e-10, convtol = 1e-8)))
  
  iter1[i,] = c(fit1$iter, fit2$iter, fit3$iter)
  cat(c(fit1$iter, fit2$iter, fit3$iter),"\n")
  
  time1[i,] = c(t1[3],t2[3],t3[3])
  cat(c(t1[3],t2[3],t3[3]),"\n")
  
  vobj1[i,] = c(fit1$varobj[fit1$iter], fit2$varobj[fit2$iter], fit3$varobj[fit3$iter])
  cat(c(fit1$varobj[fit1$iter], fit2$varobj[fit2$iter], fit3$varobj[fit3$iter]),"\n")
  
  pred1[i,] = c(norm(y.test - predict.caisa(fit1, X.test), '2'),
                norm(y.test - predict.caisa(fit2, X.test), '2'),
                norm(y.test - predict.caisa(fit3, X.test), '2'))
  cat(c(norm(y.test - predict.caisa(fit1, X.test), '2'),
        norm(y.test - predict.caisa(fit2, X.test), '2'),
        norm(y.test - predict.caisa(fit3, X.test), '2')),"\n")
}
```

```{r}
iter1 = matrix(0,20,3)
time1 = matrix(0,20,3)
vobj1 = matrix(0,20,3)
pred1 = matrix(0,20,3)
for(i in 1:20) {
seed              = 2010 + i
set.seed(seed)
data              = readRDS(filepath[i]);
n.total           = dim(data$X)[1];
p                 = dim(data$X)[2];
train.index       = sample(n.total, floor(n.total * 0.5))
test.index        = (1:n.total)[-train.index]
X                 = data$X[train.index,]
while (sort(apply(X, 2, var))[1] == 0) {
  seed = seed + 20
  set.seed(seed)
  train.index       = sample(n.total, floor(n.total * 0.5))
  test.index        = (1:n.total)[-train.index]
  X                 = data$X[train.index,]
}
X.test            = data$X[test.index,]

standardize       = FALSE

set.seed(seed)
beta              = double(p)
nzind             = which(sample(2, p, replace = TRUE, prob = c(0.01,0.99)) == 1)
beta[nzind]       = rnorm(length(nzind)) * 2
y.total           = data$X %*% beta + rnorm(n.total)

y                 = y.total[train.index]
y.test            = y.total[test.index]
sa2               = (sqrt(1.5)^(0:19) - 1)^2


iter = 1000
t1          = system.time(
  fit1       <- varmixopt(X = X, y = y, sa2 = sa2, method = "caisa",
                          stepsize = 1, max.iter = iter, tol = list(epstol = 1e-10, convtol = 1e-8)))
t2          = system.time(
  fit2       <- varmixopt(X = X, y = y, sa2 = sa2, method = "update_g",
                          stepsize = 1, max.iter = iter, tol = list(epstol = 1e-10, convtol = 1e-8)))
t3          = system.time(
  fit3       <- varmixopt(X = X, y = y, sa2 = sa2, method = "accelerated",
                          stepsize = 1, max.iter = 100,
                          tol = list(epstol = 1e-10, convtol = 1e-8)))

iter1[i,] = c(fit1$iter, fit2$iter, fit3$iter)
cat(c(fit1$iter, fit2$iter, fit3$iter),"\n")

time1[i,] = c(t1[3],t2[3],t3[3])
cat(c(t1[3],t2[3],t3[3]),"\n")

vobj1[i,] = c(fit1$varobj[fit1$iter], fit2$varobj[fit2$iter], fit3$varobj[fit3$iter])
cat(c(fit1$varobj[fit1$iter], fit2$varobj[fit2$iter], fit3$varobj[fit3$iter]),"\n")

pred1[i,] = c(norm(y.test - predict.caisa(fit1, X.test), '2'),
                  norm(y.test - predict.caisa(fit2, X.test), '2'),
                  norm(y.test - predict.caisa(fit3, X.test), '2'))
cat(c(norm(y.test - predict.caisa(fit1, X.test), '2'),
  norm(y.test - predict.caisa(fit2, X.test), '2'),
  norm(y.test - predict.caisa(fit3, X.test), '2')),"\n")
}
```

```{r}
iter1 = matrix(0,20,3)
time1 = matrix(0,20,3)
vobj1 = matrix(0,20,3)
pred1 = matrix(0,20,3)
for(i in 1:20) {
set.seed(2010 + i)
  X                <- matrix(rnorm(1010 * 1000), 1010, 1000)
  beta             <- rep(0, 1000)
  beta[1:50]       <- 5
  beta[51:200]     <- 1
  y                <- X %*% beta + rnorm(1010)
  X.test           <- matrix(rnorm(1010 * 1000), 1010, 1000)
  y.test           <- X.test %*% beta + rnorm(1010)
  sa2               = (sqrt(1.5)^(0:19) - 1)^2

iter = 1000
t1          = system.time(
  fit1       <- varmixopt(X = X, y = y, sa2 = sa2, method = "caisa",
                          stepsize = 1, max.iter = iter, tol = list(epstol = 1e-10, convtol = 1e-8)))
t2          = system.time(
  fit2       <- varmixopt(X = X, y = y, sa2 = sa2, method = "update_g",
                          stepsize = 1, max.iter = iter, tol = list(epstol = 1e-10, convtol = 1e-8)))
t3          = system.time(
  fit3       <- varmixopt(X = X, y = y, sa2 = sa2, method = "accelerated",
                          stepsize = 1, max.iter = 100,
                          tol = list(epstol = 1e-10, convtol = 1e-8)))

iter1[i,] = c(fit1$iter, fit2$iter, fit3$iter)
cat(c(fit1$iter, fit2$iter, fit3$iter),"\n")

time1[i,] = c(t1[3],t2[3],t3[3])
cat(c(t1[3],t2[3],t3[3]),"\n")

vobj1[i,] = c(fit1$varobj[fit1$iter], fit2$varobj[fit2$iter], fit3$varobj[fit3$iter])
cat(c(fit1$varobj[fit1$iter], fit2$varobj[fit2$iter], fit3$varobj[fit3$iter]),"\n")

pred1[i,] = c(norm(y.test - predict.caisa(fit1, X.test), '2'),
                  norm(y.test - predict.caisa(fit2, X.test), '2'),
                  norm(y.test - predict.caisa(fit3, X.test), '2'))
cat(c(norm(y.test - predict.caisa(fit1, X.test), '2'),
  norm(y.test - predict.caisa(fit2, X.test), '2'),
  norm(y.test - predict.caisa(fit3, X.test), '2')),"\n")
}

```

```{r}
n     = 100
p     = 99
X     = matrix(0, nrow = n, ncol = n-1)
for(jj in 1:(n-1)){ for(ii in (jj+1):n){ X[ii,jj] = 1 } }
iter1 = matrix(0,20,3)
time1 = matrix(0,20,3)
vobj1 = matrix(0,20,3)
pred1 = matrix(0,20,3)
for(i in 1:20) {
  seed              = 2010 + i
  
  ytrue             = double(n)
  ytrue[1:10]       = 1
  ytrue[31:40]      = 4
  ytrue[61:80]      = 2
  
  set.seed(seed)
  y                 = ytrue + rnorm(100)
  y.test            = ytrue
  X.test            = X
  
  standardize       = FALSE
  sa2               = (sqrt(1.5)^(0:19) - 1)^2

  t.lasso           = system.time(
  fit.lasso        <- cv.glmnet(x = X, y = y, standardize = standardize))
  fit.lasso$beta    = coef(fit.lasso)[-1]

iter = 1000
t1          = system.time(
  fit1       <- varmixopt(X = X, y = y, sa2 = sa2, method = "caisa", beta.init = fit.lasso$beta,
                          stepsize = 1, max.iter = iter, tol = list(epstol = 1e-10, convtol = 1e-8)))
t2          = system.time(
  fit2       <- varmixopt(X = X, y = y, sa2 = sa2, method = "update_g", beta.init = fit.lasso$beta,
                          stepsize = 1, max.iter = iter, tol = list(epstol = 1e-10, convtol = 1e-8)))
t3          = system.time(
  fit3       <- varmixopt(X = X, y = y, sa2 = sa2, method = "accelerated", beta.init = fit.lasso$beta,
                          stepsize = 1, max.iter = 100,
                          tol = list(epstol = 1e-10, convtol = 1e-8)))

iter1[i,] = c(fit1$iter, fit2$iter, fit3$iter)
cat(c(fit1$iter, fit2$iter, fit3$iter),"\n")

time1[i,] = c(t1[3],t2[3],t3[3])
cat(c(t1[3],t2[3],t3[3]),"\n")

vobj1[i,] = c(fit1$varobj[fit1$iter], fit2$varobj[fit2$iter], fit3$varobj[fit3$iter])
cat(c(fit1$varobj[fit1$iter], fit2$varobj[fit2$iter], fit3$varobj[fit3$iter]),"\n")

pred1[i,] = c(norm(y.test - predict.caisa(fit1, X.test), '2'),
                  norm(y.test - predict.caisa(fit2, X.test), '2'),
                  norm(y.test - predict.caisa(fit3, X.test), '2'))
cat(c(norm(y.test - predict.caisa(fit1, X.test), '2'),
  norm(y.test - predict.caisa(fit2, X.test), '2'),
  norm(y.test - predict.caisa(fit3, X.test), '2')),"\n")
}
```