---
title: "Experiment 11 (Scalability)"
author: "Youngseok Kim"
date: "5/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Scalability

```{r}
iter     = 2000
numiter  = matrix(0,20,10)
timing   = matrix(0,20,10)
betanorm = matrix(0,20,10)
for (j in 1:10) {
  c = 2^j
for (i in 1:20) {
  seed              = 2010 + i
  set.seed(seed)
  X                 = matrix(rnorm(500*500*c), 500, 500*c)
  X                 = rnorm(dim(X)[1]) * sqrt(0.5) + X * sqrt(0.5)
  X                 = scale(X)
  n                 = dim(X)[1];
  p                 = dim(X)[2];
  
  beta              = double(p)
  beta[1:10]        = rnorm(10) * 2
  y                 = X %*% beta + rnorm(n)
  
  t1          = system.time(
  fit1       <- varmixopt(X = X, y = y, sa2 = sa2, method = "caisa",
                         stepsize = 1, max.iter = iter,
                         tol = list(epstol = 1e-12, convtol = 1e-6)))
  numiter[i,j]  = fit1$iter
  timing[i,j]   = t1[3]
  betanorm[i,j] = norm(fit1$beta,'2')
  cat(c(i,j,numiter[i,j], timing[i,j], betanorm[i,j]), "\n")
}
}
```

```{r}
iter     = 2000
numiter1  = matrix(0,20,10)
timing1   = matrix(0,20,10)
betanorm1 = matrix(0,20,10)
for (j in 1:10) {
  c = 2^j
for (i in 1:20) {
  seed              = 2010 + i
  set.seed(seed)
  X                 = matrix(rnorm(2000*500*c), 2000, 500*c)
  X                 = rnorm(dim(X)[1]) * sqrt(0.5) + X * sqrt(0.5)
  X                 = scale(X)
  n                 = dim(X)[1];
  p                 = dim(X)[2];
  
  beta              = double(p)
  beta[1:10]        = rnorm(10) * 2
  y                 = X %*% beta + rnorm(n)
  
  t1          = system.time(
  fit1       <- varmixopt(X = X, y = y, sa2 = sa2, method = "caisa",
                         stepsize = 1, max.iter = iter,
                         tol = list(epstol = 1e-12, convtol = 1e-6)))
  numiter1[i,j]  = fit1$iter
  timing1[i,j]   = t1[3]
  betanorm1[i,j] = norm(fit1$beta,'2')
  cat(c(i,j,numiter1[i,j], timing1[i,j], betanorm1[i,j]), "\n")
}
}
```

```{r}
iter     = 2000
numiter3  = matrix(0,20,10)
timing3   = matrix(0,20,10)
betanorm3 = matrix(0,20,10)
for (j in 1:10) {
  c = 2^j
for (i in 1:20) {
  seed              = 2010 + i
  set.seed(seed)
  X                 = matrix(rnorm(1000*500*c), 1000, 500*c)
  X                 = rnorm(dim(X)[1]) * sqrt(0.5) + X * sqrt(0.5)
  X                 = scale(X)
  n                 = dim(X)[1];
  p                 = dim(X)[2];
  
  beta              = double(p)
  beta[1:10]        = rnorm(10) * 2
  y                 = X %*% beta + rnorm(n)
  
  t1          = system.time(
  fit1       <- varmixopt(X = X, y = y, sa2 = sa2, method = "caisa",
                         stepsize = 1, max.iter = iter,
                         tol = list(epstol = 1e-12, convtol = 1e-6)))
  numiter3[i,j]  = fit1$iter
  timing3[i,j]   = t1[3]
  betanorm3[i,j] = norm(fit1$beta,'2')
  cat(c(i,j,numiter3[i,j], timing3[i,j], betanorm3[i,j]), "\n")
}
}
```

```{r}
df = data.frame(p = rep(5 * 2^(1:10), 4),
                y = c(colMeans(timing2),colMeans(timing),
                      colMeans(timing3),colMeans(timing1)),
                n = rep(c("250","500","1000","2000"), each  = 10))
df$n = factor(df$n, levels = c("250","500","1000","2000"))
write.table(df, "dat131.txt", sep = ",")
ggplot(df) + geom_line(aes(x = p, y = y, color = n)) +
  geom_point(aes(x = p, y = y, color = n, shape = n), size = 2) +
  scale_x_continuous(trans = "log10", breaks = 5 * 2^(1:10)) +
  scale_y_continuous(trans = "log10") + 
  labs(x = "p / 1000",
       y = "elapsed time (seconds)")
```

```{r}
setwd("~/git/caisar/output")

time      = matrix(0,11,9)
time[1,]  = colMeans(matrix(read.table("Scenario1_time1.txt", sep = ",")[,2], nrow = 20))[c(1,3:10)]

time[2,]  = colMeans(matrix(read.table("Scenario1_time3.txt", sep = ",")[,2], nrow = 20))[c(1,3:10)]

time[3,]  = colMeans(matrix(read.table("Scenario1_time5.txt", sep = ",")[,2], nrow = 20))[c(1,3:10)]

time[4,]  = colMeans(matrix(read.table("Scenario2_time1.txt", sep = ",")[,2], nrow = 20))[c(2,3:10)]
time[4,1] = time[4,1] + time[4,5]

time[5,]  = colMeans(matrix(read.table("Scenario2_time3.txt", sep = ",")[,2], nrow = 20))[c(2,3:10)]
time[5,1] = time[5,1] + time[5,5]

time[6,]  = colMeans(matrix(read.table("Scenario2_time5.txt", sep = ",")[,2], nrow = 20))[c(2,3:10)]
time[6,1] = time[6,1] + time[6,5]

time[7,]  = colMeans(matrix(read.table("Scenario4_time1.txt", sep = ",")[,2], nrow = 20)) * 5.522

time[8,]  = colMeans(matrix(read.table("Scenario4_time2.txt", sep = ",")[,2], nrow = 20)) * 1.323

time[9,]  = colMeans(matrix(read.table("Scenario4_time3.txt", sep = ",")[,2], nrow = 20)) * 1.595

a         = colMeans(matrix(read.table("Scenario3_time1.txt", sep = ",")[,2], nrow = 20))[2:13] * 0.043
a[1]      = a[1] + a[12]
time[10,] = a[2:10]

a         = colMeans(matrix(read.table("Scenario3_time2.txt", sep = ",")[,2], nrow = 20))[2:13] * 0.043
a[1]      = a[1] + a[12]
time[11,] = a[2:10]

df = data.frame(time = c(time),
                fit  = rep(read.table("Scenario1_time1.txt", sep = ",")
                           [seq(1,200,20),1][c(1,3:10)], each = 11))
```
