---
title: "Experiment 7 (Design 3)"
author: "Youngseok Kim"
date: "4/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

This .Rmd file is to reproduce the result for Figure , Design 4.

### Load libraries, packages and codes

We load libraries, packages and codes for the simulation and for the plotting.

```{r}
library(Matrix); library(Rcpp); library(varbvs); library(ggplot2); library(cowplot);
library(glmnet); library(susieR); library(BGLR); library(DNAcopy); library(bcp);
library(genlasso)
sourceCpp("~/git/caisar/src/caisa_caisa.cpp");
sourceCpp("~/git/caisar/src/caisa_acceleration.cpp");
sourceCpp("~/git/caisar/src/caisa_update_g.cpp");
source("~/git/caisar/R/varmixopt.R");
source("~/git/caisar/R/misc.R");
source("~/git/caisar/R/etc.R");
source("~/git/caisar/R/changepoint.R");
```

### Simulation setting

#### Design matrix

```{r}
n     = 100
p     = 99
X     = matrix(0, nrow = n, ncol = n-1)
for(jj in 1:(n-1)){ for(ii in (jj+1):n){ X[ii,jj] = 1 } }
```

## Simulation

### Scenario 1

```{r}
pred1 = matrix(0,20,13)
t1    = matrix(0,20,13)
for (i in 1:20) {
  seed              = 2010 + i
  
  ytrue             = double(n)
  ytrue[1:10]       = 1
  ytrue[31:40]      = 4
  ytrue[61:80]      = 2
  
  set.seed(seed)
  y                 = ytrue + rnorm(100)
  y.test            = ytrue
  X.test            = X
  
  standardize       = FALSE
  sa2               = (sqrt(1.5)^(0:19) - 1)^2

  t.binseg          = system.time(
  fit.binseg       <- segment_cp(y))
  t.bcp             = system.time(
  fit.bcp          <- bcp_cp(y))
  t.trendfilter     = system.time(
  fit.trendfilter  <- tf_cp(y))
  t.susie           = system.time(
  fit.susie        <- susie(X = X, Y = y, L = length(nzind), standardize = standardize))
  fit.susie$beta    = coef(fit.susie)[-1]
  t.lasso           = system.time(
  fit.lasso        <- cv.glmnet(x = X, y = y, standardize = standardize))
  fit.lasso$beta    = coef(fit.lasso)[-1]
  path.order        = lasso_order(fit.lasso$glmnet.fit)
  univar.order      = order(abs(t(X) %*% y), decreasing = TRUE)
  
  t.caisa           = system.time(
  fit.caisa        <- varmixopt(X = X, y = y, sa2 = sa2, method = "update_g",
                               stepsize = 1, max.iter = 2000, standardize = standardize,
                               tol = list(epstol = 1e-12, convtol = 1e-8)))
  
  beta.init         = fit.trendfilter$yhat[-1] - fit.trendfilter$yhat[-n]
  t.caisa2          = system.time(
  fit.caisa2       <- varmixopt(X = X, y = y, sa2 = sa2, method = "update_g",
                               stepsize = 1, max.iter = 2000, beta.init = beta.init, standardize = standardize,
                               tol = list(epstol = 1e-12, convtol = 1e-8)))
  
  t.ridge           = system.time(
  fit.ridge        <- cv.glmnet(x = X, y = y, alpha = 0, standardize = standardize))
  fit.ridge$beta    = coef(fit.ridge)[-1]
  t.enet = system.time(
  fit.enet         <- cv.glmnet(x = X, y = y, alpha = 0.9, standardize = standardize))
  fit.enet$beta     = coef(fit.enet)[-1]
  t.blasso          = system.time(
  fit.blasso       <- BGLR(y, ETA = list(list(X = X, model="BL", standardize = standardize)), verbose = FALSE))
  fit.blasso$beta   = fit.blasso$ETA[[1]]$b
  t.bayesB          = system.time(
  fit.bayesB       <- BGLR(y, ETA = list(list(X = X, model="BayesB", standardize = standardize)), verbose = FALSE))
  fit.bayesB$beta   = fit.blasso$ETA[[1]]$b * fit.bayesB$ETA[[1]]$d
  t.varbvs          = system.time(
  fit.varbvs       <- varbvs(X, Z = NULL, y, verbose = FALSE));
  fit.varbvs$beta   = rowSums(fit.varbvs$alpha * fit.varbvs$mu)
  t.L0Learn         = system.time(
  fit.L0Learn      <- L0Learn.cvfit(X, y, nFolds=10))
  lambda.min        = fit.L0Learn$fit$lambda[[1]][which.min(fit.L0Learn$cvMeans[[1]])]
  
  pred1[i,] =  c("caisa"      = norm(y.test - predict.caisa(fit.caisa, X.test), '2'),
                 "caisa2"     = norm(y.test - predict.caisa(fit.caisa2, X.test), '2'),
                 "susie"      = norm(y.test - predict.susie(fit.susie, X.test), '2'),
                 "varbvs"     = norm(y.test - predict(fit.varbvs, X.test), '2'),
                 "L0Learn"    = norm(y.test - predict(fit.L0Learn, newx = X.test, lambda = lambda.min)@x, '2'),
                 "lasso"      = norm(y.test - predict.glmnet(fit.lasso$glmnet.fit, newx = X.test,
                                                                 s = fit.lasso$lambda.1se), '2'),
                 "ridge"      = norm(y.test - predict.glmnet(fit.ridge$glmnet.fit, newx = X.test,
                                                                 s = fit.ridge$lambda.1se), '2'),
                 "enet"       = norm(y.test - predict.glmnet(fit.enet$glmnet.fit, newx = X.test,
                                                                 s = fit.enet$lambda.1se), '2'),
                 "blasso"     = norm(y.test - fit.blasso$yHat, '2'),
                 "bayesB"     = norm(y.test - fit.bayesB$yHat, '2'),
                 "bcp"        = norm(y.test - fit.bcp$yhat, '2'),
                 "binseg"     = norm(y.test - fit.binseg$yhat, '2'),
                 "flasso"     = norm(y.test - fit.trendfilter$yhat, '2'))
  t1[i,] =     c("caisa"      = t.caisa[3],
                 "caisa2"      = t.caisa2[3],
                 "susie"      = t.susie[3],
                 "varbvs"     = t.varbvs[3],
                 "L0Learn"    = t.L0Learn[3],
                 "lasso"      = t.lasso[3],
                 "ridge"      = t.ridge[3],
                 "enet"       = t.enet[3],
                 "blasso"     = t.blasso[3],
                 "bayesB"     = t.bayesB[3],
                 "bcp"        = t.bcp[3],
                 "binseg"     = t.binseg[3],
                 "flasso"     = t.trendfilter[3])
  cat(pred1[i,],"\n")
  cat(t1[i,],"\n")
}
```

```{r}
pred2 = matrix(0,20,13)
t2    = matrix(0,20,13)
for (i in 1:20) {
  seed              = 2010 + i
  
  ytrue             = double(n)
  ytrue[50:51]      = 8
  
  set.seed(seed)
  y                 = ytrue + rnorm(100)
  y.test            = ytrue
  X.test            = X
  
  standardize       = FALSE
  sa2               = (sqrt(1.5)^(0:19) - 1)^2

  t.binseg          = system.time(
  fit.binseg       <- segment_cp(y))
  t.bcp             = system.time(
  fit.bcp          <- bcp_cp(y))
  t.trendfilter     = system.time(
  fit.trendfilter  <- tf_cp(y))
  t.susie           = system.time(
  fit.susie        <- susie(X = X, Y = y, L = length(nzind), standardize = standardize))
  fit.susie$beta    = coef(fit.susie)[-1]
  t.lasso           = system.time(
  fit.lasso        <- cv.glmnet(x = X, y = y, standardize = standardize))
  fit.lasso$beta    = coef(fit.lasso)[-1]
  path.order        = lasso_order(fit.lasso$glmnet.fit)
  univar.order      = order(abs(t(X) %*% y), decreasing = TRUE)
  
  t.caisa           = system.time(
  fit.caisa        <- varmixopt(X = X, y = y, sa2 = sa2, method = "update_g",
                               stepsize = 1, max.iter = 2000, standardize = standardize,
                               tol = list(epstol = 1e-12, convtol = 1e-8)))
  
  beta.init         = fit.trendfilter$yhat[-1] - fit.trendfilter$yhat[-n]
  t.caisa2          = system.time(
  fit.caisa2       <- varmixopt(X = X, y = y, sa2 = sa2, method = "update_g",
                               stepsize = 1, max.iter = 2000, beta.init = beta.init, standardize = standardize,
                               tol = list(epstol = 1e-12, convtol = 1e-8)))
  
  t.ridge           = system.time(
  fit.ridge        <- cv.glmnet(x = X, y = y, alpha = 0, standardize = standardize))
  fit.ridge$beta    = coef(fit.ridge)[-1]
  t.enet = system.time(
  fit.enet         <- cv.glmnet(x = X, y = y, alpha = 0.9, standardize = standardize))
  fit.enet$beta     = coef(fit.enet)[-1]
  t.blasso          = system.time(
  fit.blasso       <- BGLR(y, ETA = list(list(X = X, model="BL", standardize = standardize)), verbose = FALSE))
  fit.blasso$beta   = fit.blasso$ETA[[1]]$b
  t.bayesB          = system.time(
  fit.bayesB       <- BGLR(y, ETA = list(list(X = X, model="BayesB", standardize = standardize)), verbose = FALSE))
  fit.bayesB$beta   = fit.blasso$ETA[[1]]$b * fit.bayesB$ETA[[1]]$d
  t.varbvs          = system.time(
  fit.varbvs       <- varbvs(X, Z = NULL, y, verbose = FALSE));
  fit.varbvs$beta   = rowSums(fit.varbvs$alpha * fit.varbvs$mu)
  t.L0Learn         = system.time(
  fit.L0Learn      <- L0Learn.cvfit(X, y, nFolds=10))
  lambda.min        = fit.L0Learn$fit$lambda[[1]][which.min(fit.L0Learn$cvMeans[[1]])]

  pred2[i,] =  c("caisa"      = norm(y.test - predict.caisa(fit.caisa, X.test), '2'),
                 "caisa2"     = norm(y.test - predict.caisa(fit.caisa2, X.test), '2'),
                 "susie"      = norm(y.test - predict.susie(fit.susie, X.test), '2'),
                 "varbvs"     = norm(y.test - predict(fit.varbvs, X.test), '2'),
                 "L0Learn"    = norm(y.test - predict(fit.L0Learn, newx = X.test, lambda = lambda.min)@x, '2'),
                 "lasso"      = norm(y.test - predict.glmnet(fit.lasso$glmnet.fit, newx = X.test,
                                                                 s = fit.lasso$lambda.1se), '2'),
                 "ridge"      = norm(y.test - predict.glmnet(fit.ridge$glmnet.fit, newx = X.test,
                                                                 s = fit.ridge$lambda.1se), '2'),
                 "enet"       = norm(y.test - predict.glmnet(fit.enet$glmnet.fit, newx = X.test,
                                                                 s = fit.enet$lambda.1se), '2'),
                 "blasso"     = norm(y.test - fit.blasso$yHat, '2'),
                 "bayesB"     = norm(y.test - fit.bayesB$yHat, '2'),
                 "bcp"        = norm(y.test - fit.bcp$yhat, '2'),
                 "binseg"     = norm(y.test - fit.binseg$yhat, '2'),
                 "flasso"     = norm(y.test - fit.trendfilter$yhat, '2'))
  t2[i,] =     c("caisa"      = t.caisa[3],
                 "caisa2"      = t.caisa2[3],
                 "susie"      = t.susie[3],
                 "varbvs"     = t.varbvs[3],
                 "L0Learn"    = t.L0Learn[3],
                 "lasso"      = t.lasso[3],
                 "ridge"      = t.ridge[3],
                 "enet"       = t.enet[3],
                 "blasso"     = t.blasso[3],
                 "bayesB"     = t.bayesB[3],
                 "bcp"        = t.bcp[3],
                 "binseg"     = t.binseg[3],
                 "flasso"     = t.trendfilter[3])
  cat(pred2[i,],"\n")
  cat(t2[i,],"\n")
}
```

## Save results

We save results as follows. One may find .txt files in the following path.

```{r}
df.pred1 = data.frame("fit" = rep(c("CAISA","CAISA2","SUSIE","VARBVS","L0Learn","LASSO",
                                    "RIDGE","E-NET","BLASSO","BayesB","BCP","BinSeg","FLASSO"), each = 20),
                      "pred" = c(pred1/pred1[,2]))
df.pred2 = data.frame("fit" = rep(c("CAISA","CAISA2","SUSIE","VARBVS","L0Learn","LASSO",
                                    "RIDGE","E-NET","BLASSO","BayesB","BCP","BinSeg","FLASSO"), each = 20),
                      "pred" = c(pred2/pred2[,2]))
df.time1 = data.frame("fit" = rep(c("CAISA","CAISA2","SUSIE","VARBVS","L0Learn","LASSO",
                                    "RIDGE","E-NET","BLASSO","BayesB","BCP","BinSeg","FLASSO"), each = 20),
                      "time" = c(t1/t1[,2]))
df.time2 = data.frame("fit" = rep(c("CAISA","CAISA2","SUSIE","VARBVS","L0Learn","LASSO",
                                    "RIDGE","E-NET","BLASSO","BayesB","BCP","BinSeg","FLASSO"), each = 20),
                      "time" = c(t2/t2[,2]))
write.table(df.pred1, "~/git/caisar/output/Scenario3_pred1.txt", sep = ",")
write.table(df.pred2, "~/git/caisar/output/Scenario3_pred2.txt", sep = ",")
write.table(df.time1, "~/git/caisar/output/Scenario3_time1.txt", sep = ",")
write.table(df.time2, "~/git/caisar/output/Scenario3_time2.txt", sep = ",")
```

```{r}
df1      = data.frame("fit" = rep(c("CAISA","CAISA2","SUSIE","VARBVS","L0Learn","LASSO",
                                    "RIDGE","E-NET","BLASSO","BayesB","BCP","BinSeg","FLASSO"), each = 20),
                      "pred" = c(pred1/pred1[,2]))
df2      = data.frame("fit" = rep(c("CAISA","CAISA2","SUSIE","VARBVS","L0Learn","LASSO",
                                    "RIDGE","E-NET","BLASSO","BayesB","BCP","BinSeg","FLASSO"), each = 20),
                      "pred" = c(pred2/pred2[,2]))
write.table(df1, "~/git/caisar/output/dat91.txt", sep = ",")
write.table(df2, "~/git/caisar/output/dat92.txt", sep = ",")
```