# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

caisa_acc <- function(X, w, sa2, pi, beta, r, sigma2, maxiter, miniter, convtol, epstol, stepsize, updatesigma, verbose) {
    .Call('_varbvs2_caisa_acc', PACKAGE = 'varbvs2', X, w, sa2, pi, beta, r, sigma2, maxiter, miniter, convtol, epstol, stepsize, updatesigma, verbose)
}

caisa_em <- function(X, w, sa2, pi, beta, r, sigma2, maxiter, miniter, convtol, epstol, stepsize, updatesigma, verbose) {
    .Call('_varbvs2_caisa_em', PACKAGE = 'varbvs2', X, w, sa2, pi, beta, r, sigma2, maxiter, miniter, convtol, epstol, stepsize, updatesigma, verbose)
}

caisa_g <- function(X, w, sa2, phi, pi, beta, r, sigma2, maxiter, miniter, convtol, epstol, stepsize, updatesigma, verbose) {
    .Call('_varbvs2_caisa_g', PACKAGE = 'varbvs2', X, w, sa2, phi, pi, beta, r, sigma2, maxiter, miniter, convtol, epstol, stepsize, updatesigma, verbose)
}

caisa_order <- function(X, w, sa2, pi, beta, r, sigma2, o, maxiter, miniter, convtol, epstol, stepsize, updatesigma, verbose) {
    .Call('_varbvs2_caisa_order', PACKAGE = 'varbvs2', X, w, sa2, pi, beta, r, sigma2, o, maxiter, miniter, convtol, epstol, stepsize, updatesigma, verbose)
}

