# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

caisa_rcpp <- function(X, y, w, sa2, pi, beta, r, sigma2, o, maxiter, miniter, convtol, epstol, method_q, updatepi, updatesigma, verbose) {
    .Call('_mr_ash_alpha_caisa_rcpp', PACKAGE = 'mr.ash.alpha', X, y, w, sa2, pi, beta, r, sigma2, o, maxiter, miniter, convtol, epstol, method_q, updatepi, updatesigma, verbose)
}

random_order <- function(p, numiter) {
    .Call('_mr_ash_alpha_random_order', PACKAGE = 'mr.ash.alpha', p, numiter)
}

